name: SaaSYamlTest

servers:
  - name: mainServer
    host: example.com

user_paths:
  - name: UserLoginPath
    steps:
      - request:
          url: http://example.com/login
          method: GET

populations:
  - name: LoadPopulation
    user_paths:
      - name: UserLoginPath
        distribution: 100%

scenarios:
  - name: BasicScenario
    populations:
      - name: LoadPopulation
        constant_load:
          users: 10
          duration: 1m
